name: Generate Swagger & License

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # 允许 commit & push

jobs:
  generate:
    # 避免死循环
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]'))

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}

      # 1. 安装工具
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Install tools
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/google/addlicense@latest

      # 2. 生成代码
      - name: Generate Swagger and License
        run: |
          make swagger
          make license

      # 3. 自动提交
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/
          git add .

          if ! git diff --staged --quiet; then
            git commit -m "chore(ci): auto-generate swagger & license [skip ci]"
            git push
          else
            echo "No generated changes detected."
          fi
